//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANH
    {
        public string ID { get; set; }
        public string LINK { get; set; }
        public string ACCID { get; set; }
        public Nullable<int> LOAI { get; set; }
    
        public virtual LOLACC LOLACC { get; set; }
    }
}
