//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAODICH
    {
        public string ID { get; set; }
        public string THANHVIENID { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<long> SOTIEN { get; set; }
        public Nullable<System.DateTime> THOIDIEM { get; set; }
        public string MAGIAODICH { get; set; }
    
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
