//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOITHOAI
    {
        public HOITHOAI()
        {
            this.TINNHANs = new HashSet<TINNHAN>();
        }
    
        public string ID { get; set; }
        public string THANHVIEN { get; set; }
    
        public virtual THANHVIEN THANHVIEN1 { get; set; }
        public virtual ICollection<TINNHAN> TINNHANs { get; set; }
    }
}
