//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAcc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopAccEntities : DbContext
    {
        public ShopAccEntities()
            : base("name=ShopAccEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACC_SKIN> ACC_SKIN { get; set; }
        public DbSet<LOLACC> LOLACCs { get; set; }
        public DbSet<RANK> RANKs { get; set; }
        public DbSet<SKIN> SKINs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<THANHVIEN> THANHVIENs { get; set; }
    }
}
