//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAcc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopAccEntities1 : DbContext
    {
        public ShopAccEntities1()
            : base("name=ShopAccEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACC_SKIN> ACC_SKIN { get; set; }
        public virtual DbSet<LOLACC> LOLACCs { get; set; }
        public virtual DbSet<RANK> RANKs { get; set; }
        public virtual DbSet<SKIN> SKINs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THANHVIEN> THANHVIENs { get; set; }
        public virtual DbSet<GIAODICH> GIAODICHes { get; set; }
        public virtual DbSet<ANH> ANHs { get; set; }
        public virtual DbSet<HOITHOAI> HOITHOAIs { get; set; }
        public virtual DbSet<TINNHAN> TINNHANs { get; set; }
    }
}
