//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANK
    {
        public RANK()
        {
            this.LOLACCs = new HashSet<LOLACC>();
        }
    
        public string ID { get; set; }
        public string TEN { get; set; }
        public string HINHANH { get; set; }
    
        public virtual ICollection<LOLACC> LOLACCs { get; set; }
    }
}
