//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        public THANHVIEN()
        {
            this.GIAODICHes = new HashSet<GIAODICH>();
            this.LOLACCs = new HashSet<LOLACC>();
            this.HOITHOAIs = new HashSet<HOITHOAI>();
            this.TINNHANs = new HashSet<TINNHAN>();
        }
    
        public string ID { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string FULLNAME { get; set; }
        public string AVATAR { get; set; }
        public Nullable<int> MONEY { get; set; }
        public Nullable<int> QUYEN { get; set; }
    
        public virtual ICollection<GIAODICH> GIAODICHes { get; set; }
        public virtual ICollection<LOLACC> LOLACCs { get; set; }
        public virtual ICollection<HOITHOAI> HOITHOAIs { get; set; }
        public virtual ICollection<TINNHAN> TINNHANs { get; set; }
    }
}
