//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINNHAN
    {
        public string ID { get; set; }
        public string HOITHOAIID { get; set; }
        public string NGUOIGUI { get; set; }
        public string TINNHAN1 { get; set; }
        public Nullable<System.DateTime> NGAYGUI { get; set; }
    
        public virtual HOITHOAI HOITHOAI { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
